services:
  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=qwerty"
      - "POSTGRES_DB=pv311_web_api"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - pv311_db:/var/lib/postgresql/data
    networks:
      - "api_nt"

  api:
    build: pv311_web_api/
    image: potapchuk22/pv311_api
    container_name: api
    ports:
      - "7223:8080"
    environment:
      - "ConnectionStrings__NpgSql=User ID=postgres;Password=qwerty;Host=db;Port=5432;Database=pv311_web_api;"
      - "Cors__AllowedOrigin=http://localhost"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - pv311_api_files:/app/wwwroot
    networks:
      - "api_nt"

  front:
    build: 
      context: dashboard/
      args:
        REACT_APP_API_URL: http://localhost:7223/api/
        REACT_APP_API_IMAGES_URL: http://localhost:7223/images/
    image: potapchuk22/pv311_react
    container_name: front
    ports:
      - "80:3000"
    depends_on:
      - "api"

networks:
  api_nt:

volumes:
  pv311_api_files:
    name: pv311_api
  pv311_db:
    driver: local
    name: pv311_db